Add Mayhem
mayhemheroes/adsb_deku pull request #1
Opened 2022-05-17 00:59 UTC by nottirb

- Added a Dockerfile for fuzz testing
- Added Mayhemfile(s) for fuzz testing
- Added a `mayhem.yml` file for automatically running fuzz tests with Mayhem using the `mcode` action

2022-07-06 17:30 UTC, xansec requested changes
Please make the requested changes.

2022-07-06 17:30 UTC, xansec commented on Mayhemfile
> +project: adsb-deku
Is it possible to rename this from fuzz_target_1 to something that describes what's being fuzzed? I know this was what it was called upstream but I'd prefer if we can clarify targets

2022-07-06 23:34 UTC, nottirb commented on Mayhemfile
> +project: adsb-deku
I'll work on getting this changed. This change makes sense to me.

2022-07-07 03:04 UTC, xansec commented
Thanks, LGTM!

2022-07-07 03:04 UTC, merged

2022-07-07 03:19 UTC, nottirb commented
It looks like there might be a slight issue here, though I'm not quite sure what it is. For some reason the mcode action is saying that it isn't able to run the command in the mayhemfile because it doesn't exist.

I pulled the image that the github action built and pushed, but when I checked it, it had the command/binary and was able to run on my computer just fine. (Building the Dockerfile and calling ``mayhem run -f mayhem/frame_from_bytes.mayhemfile .`` would work on my machine)

Any idea why this might be happening?